default_agent: excel_mcp_server
agents:
  excel_mcp_server:
    name: excel_mcp_server
    entrypoint: /Users/peijun/excel-mcp/mcp-server/mcp_server.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/peijun/excel-mcp/mcp-server
    aws:
      execution_role: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-50200630cb
      execution_role_auto_create: false
      account: 'YOUR_AWS_ACCOUNT_ID'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-YOUR_AWS_ACCOUNT_ID-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: excel_mcp_server-fya1KHHya1
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:YOUR_AWS_ACCOUNT_ID:runtime/excel_mcp_server-fya1KHHya1
      agent_session_id: f5907716-d47a-4e71-8328-07bf9fded868
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: excel_mcp_server_mem-dG4B9fAIPU
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:YOUR_AWS_ACCOUNT_ID:memory/excel_mcp_server_mem-dG4B9fAIPU
      memory_name: excel_mcp_server_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
