default_agent: excel_mcp_oauth
agents:
  excel_mcp_oauth:
    name: excel_mcp_oauth
    entrypoint: mcp_server.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: ./mcp-server
    aws:
      execution_role: arn:aws:iam::{account-id}:role/{your-execution-role}
      execution_role_auto_create: false
      account: '{account-id}'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://{your-s3-bucket}
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.{region}.amazonaws.com/{user-pool-id}/.well-known/openid-configuration
        allowedClients:
        - '{your-client-id}'
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
